import { ComponentInfo, ComponentSpecification, ReplacementComponent } from '@/types/component';

export const mockComponentInfo: ComponentInfo = {
    partNumber: 'LM7805CT',
    name: 'Linear Voltage Regulator',
    manufacturer: 'Texas Instruments',
    status: 'EOL',
    category: 'Power Management',
    description: '5V 1.5A Positive Voltage Regulator, TO-220 Package',
};

export const mockSpecifications: ComponentSpecification[] = [
    { id: '1', parameter: 'Input Voltage', value: '7-35', unit: 'V' },
    { id: '2', parameter: 'Output Voltage', value: '5', unit: 'V' },
    { id: '3', parameter: 'Output Current', value: '1.5', unit: 'A' },
    { id: '4', parameter: 'Package Type', value: 'TO-220', unit: '' },
    { id: '5', parameter: 'Operating Temperature', value: '-40 to +125', unit: '°C' },
    { id: '6', parameter: 'Dropout Voltage', value: '2', unit: 'V' },
    { id: '7', parameter: 'Quiescent Current', value: '6', unit: 'mA' },
    { id: '8', parameter: 'Line Regulation', value: '0.01', unit: '%/V' },
];

export const mockReplacements: ReplacementComponent[] = [
    {
        id: '1',
        partNumber: 'L7805CV',
        name: 'Positive Voltage Regulator',
        manufacturer: 'STMicroelectronics',
        compatibilityScore: 98,
        riskLevel: 'Low',
        status: 'Active',
        formMatch: 100,
        fitMatch: 100,
        functionMatch: 95,
        matchedParameters: [
            { parameter: 'Output Voltage', originalValue: '5V', replacementValue: '5V', isMatch: true },
            { parameter: 'Output Current', originalValue: '1.5A', replacementValue: '1.5A', isMatch: true },
            { parameter: 'Package Type', originalValue: 'TO-220', replacementValue: 'TO-220', isMatch: true },
            { parameter: 'Input Voltage Range', originalValue: '7-35V', replacementValue: '7-35V', isMatch: true },
        ],
        mismatchedParameters: [
            { parameter: 'Quiescent Current', originalValue: '6mA', replacementValue: '5.5mA', isMatch: false, severity: 'info' },
        ],
        warnings: [],
        aiExplanation: 'The L7805CV is an excellent drop-in replacement for the LM7805CT. Both components share identical pinout, package (TO-220), and electrical specifications. The STMicroelectronics variant has a slightly lower quiescent current (5.5mA vs 6mA), which is actually an improvement. No PCB modifications required.',
    },
    {
        id: '2',
        partNumber: 'MC7805BDTG',
        name: 'Linear Voltage Regulator',
        manufacturer: 'onsemi',
        compatibilityScore: 92,
        riskLevel: 'Low',
        status: 'Active',
        formMatch: 95,
        fitMatch: 100,
        functionMatch: 92,
        matchedParameters: [
            { parameter: 'Output Voltage', originalValue: '5V', replacementValue: '5V', isMatch: true },
            { parameter: 'Output Current', originalValue: '1.5A', replacementValue: '1.0A', isMatch: false, severity: 'warning' },
            { parameter: 'Package Type', originalValue: 'TO-220', replacementValue: 'DPAK', isMatch: false, severity: 'warning' },
        ],
        mismatchedParameters: [
            { parameter: 'Package Type', originalValue: 'TO-220', replacementValue: 'DPAK', isMatch: false, severity: 'warning' },
            { parameter: 'Output Current', originalValue: '1.5A', replacementValue: '1.0A', isMatch: false, severity: 'warning' },
        ],
        warnings: ['Different package type - PCB footprint change required', 'Lower current rating - verify system requirements'],
        aiExplanation: 'The MC7805BDTG offers similar voltage regulation performance but uses a surface-mount DPAK package instead of through-hole TO-220. This requires PCB footprint changes. Additionally, the maximum output current is 1.0A vs 1.5A - verify your application\'s current requirements before selecting this option.',
    },
    {
        id: '3',
        partNumber: 'UA7805CKCS',
        name: 'Positive Voltage Regulator',
        manufacturer: 'Texas Instruments',
        compatibilityScore: 96,
        riskLevel: 'Low',
        status: 'Active',
        formMatch: 100,
        fitMatch: 100,
        functionMatch: 94,
        matchedParameters: [
            { parameter: 'Output Voltage', originalValue: '5V', replacementValue: '5V', isMatch: true },
            { parameter: 'Output Current', originalValue: '1.5A', replacementValue: '1.5A', isMatch: true },
            { parameter: 'Package Type', originalValue: 'TO-220', replacementValue: 'TO-220', isMatch: true },
        ],
        mismatchedParameters: [
            { parameter: 'Operating Temperature', originalValue: '-40 to +125°C', replacementValue: '0 to +125°C', isMatch: false, severity: 'warning' },
        ],
        warnings: ['Narrower operating temperature range - not suitable for sub-zero applications'],
        aiExplanation: 'The UA7805CKCS from Texas Instruments is a direct electrical and mechanical replacement. However, it has a narrower operating temperature range (0°C to +125°C vs -40°C to +125°C). If your application operates in environments below 0°C, consider alternative options.',
    },
    {
        id: '4',
        partNumber: 'LM2940CT-5.0',
        name: 'Low Dropout Regulator',
        manufacturer: 'Texas Instruments',
        compatibilityScore: 78,
        riskLevel: 'Medium',
        status: 'Active',
        formMatch: 100,
        fitMatch: 85,
        functionMatch: 75,
        matchedParameters: [
            { parameter: 'Output Voltage', originalValue: '5V', replacementValue: '5V', isMatch: true },
            { parameter: 'Package Type', originalValue: 'TO-220', replacementValue: 'TO-220', isMatch: true },
        ],
        mismatchedParameters: [
            { parameter: 'Output Current', originalValue: '1.5A', replacementValue: '1.0A', isMatch: false, severity: 'warning' },
            { parameter: 'Input Voltage Range', originalValue: '7-35V', replacementValue: '6-26V', isMatch: false, severity: 'warning' },
            { parameter: 'Dropout Voltage', originalValue: '2V', replacementValue: '0.5V', isMatch: false, severity: 'info' },
        ],
        warnings: ['Lower maximum input voltage', 'Reduced output current capacity', 'Different regulator topology (LDO)'],
        aiExplanation: 'The LM2940CT-5.0 is a Low Dropout Regulator offering improved efficiency with only 0.5V dropout. However, several key differences exist: lower max input voltage (26V vs 35V), reduced output current (1.0A vs 1.5A). This is a functional replacement only if your input voltage stays below 26V and current draw is under 1.0A.',
    },
    {
        id: '5',
        partNumber: 'NCV7805BD2TG',
        name: 'Automotive Voltage Regulator',
        manufacturer: 'onsemi',
        compatibilityScore: 65,
        riskLevel: 'High',
        status: 'Active',
        formMatch: 60,
        fitMatch: 70,
        functionMatch: 90,
        matchedParameters: [
            { parameter: 'Output Voltage', originalValue: '5V', replacementValue: '5V', isMatch: true },
            { parameter: 'Output Current', originalValue: '1.5A', replacementValue: '1.5A', isMatch: true },
        ],
        mismatchedParameters: [
            { parameter: 'Package Type', originalValue: 'TO-220', replacementValue: 'D2PAK', isMatch: false, severity: 'critical' },
            { parameter: 'Mounting', originalValue: 'Through-hole', replacementValue: 'Surface Mount', isMatch: false, severity: 'critical' },
        ],
        warnings: ['Major package change - significant PCB redesign required', 'Surface mount vs through-hole', 'Automotive-grade pricing premium'],
        aiExplanation: 'The NCV7805BD2TG is an automotive-qualified regulator with excellent reliability but uses a completely different D2PAK surface-mount package. This would require significant PCB redesign including new footprint, different thermal management approach, and reflow soldering capability. Only recommended if transitioning to automotive-grade design.',
    },
];
